# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windows1.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(833, 713)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.verticalLayout_9.addWidget(self.label)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setAcceptDrops(False)
        self.treeView.setObjectName("treeView")
        self.verticalLayout.addWidget(self.treeView)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.horizontalLayout_10.addLayout(self.verticalLayout_5)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_10.addWidget(self.line_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.treeView_2 = QtWidgets.QTreeView(self.centralwidget)
        self.treeView_2.setAcceptDrops(False)
        self.treeView_2.setObjectName("treeView_2")
        self.verticalLayout_2.addWidget(self.treeView_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.horizontalLayout_10.addLayout(self.verticalLayout_6)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_9.addWidget(self.line)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.tab_7)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.tab_7)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.tab_7)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_7)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.tab_7)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_7)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.tab_9)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.comboBox_6 = QtWidgets.QComboBox(self.tab_9)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.tab_9)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.comboBox_7 = QtWidgets.QComboBox(self.tab_9)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.tab_9)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.comboBox_8 = QtWidgets.QComboBox(self.tab_9)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_14 = QtWidgets.QLabel(self.tab_9)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_17.addWidget(self.label_14)
        self.comboBox_13 = QtWidgets.QComboBox(self.tab_9)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.horizontalLayout_17.addWidget(self.comboBox_13)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.tab_9)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_9)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_9 = QtWidgets.QLabel(self.tab_10)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_12.addWidget(self.label_9)
        self.comboBox_9 = QtWidgets.QComboBox(self.tab_10)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.horizontalLayout_12.addWidget(self.comboBox_9)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_10 = QtWidgets.QLabel(self.tab_10)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_13.addWidget(self.label_10)
        self.comboBox_10 = QtWidgets.QComboBox(self.tab_10)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.horizontalLayout_13.addWidget(self.comboBox_10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_11 = QtWidgets.QLabel(self.tab_10)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_14.addWidget(self.label_11)
        self.comboBox_11 = QtWidgets.QComboBox(self.tab_10)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.horizontalLayout_14.addWidget(self.comboBox_11)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_12 = QtWidgets.QLabel(self.tab_10)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_19.addWidget(self.label_12)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem4)
        self.checkBox = QtWidgets.QCheckBox(self.tab_10)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_19.addWidget(self.checkBox)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_19.addWidget(self.lineEdit_4)
        self.label_16 = QtWidgets.QLabel(self.tab_10)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_19.addWidget(self.label_16)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_19.addWidget(self.lineEdit_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_13 = QtWidgets.QLabel(self.tab_10)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_15.addWidget(self.label_13)
        self.comboBox_12 = QtWidgets.QComboBox(self.tab_10)
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.horizontalLayout_15.addWidget(self.comboBox_12)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_15 = QtWidgets.QLabel(self.tab_10)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_16.addWidget(self.label_15)
        self.comboBox_14 = QtWidgets.QComboBox(self.tab_10)
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.horizontalLayout_16.addWidget(self.comboBox_14)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.tabWidget.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_11)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.listView = QtWidgets.QListView(self.tab_11)
        self.listView.setObjectName("listView")
        self.verticalLayout_8.addWidget(self.listView)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem5)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_18.addWidget(self.pushButton_5)
        spacerItem6 = QtWidgets.QSpacerItem(37, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        self.progressBar = QtWidgets.QProgressBar(self.tab_11)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_8.addWidget(self.progressBar)
        self.tabWidget.addTab(self.tab_11, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tabWidget.addTab(self.tab_8, "")
        self.verticalLayout_9.addWidget(self.tabWidget)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem7 = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_11.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_11.addWidget(self.pushButton_3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "集群转码系统-脱离版1.0"))
        self.pushButton.setText(_translate("MainWindow", "Input"))
        self.pushButton_2.setText(_translate("MainWindow", "Output"))
        self.label_2.setText(_translate("MainWindow", "Preset:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "ProRes 422"))
        self.comboBox.setItemText(1, _translate("MainWindow", "ProRes 422 LT"))
        self.comboBox.setItemText(2, _translate("MainWindow", "x264"))
        self.label_3.setText(_translate("MainWindow", "Video Format:"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Apple ProRes 422"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Apple ProRes 422 LT"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "libx264"))
        self.label_4.setText(_translate("MainWindow", "Audio Format:"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Uncompressed(PCM)"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "AAC"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "傻瓜模式"))
        self.label_5.setText(_translate("MainWindow", "Preset:"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "ProRes 422"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "ProRes 422 LT"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "x264"))
        self.label_6.setText(_translate("MainWindow", "Video Format:"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "ProRes 422"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "ProRes 422 LT"))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "x264"))
        self.label_7.setText(_translate("MainWindow", "Audio Format:"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "ProRes 422"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "ProRes 422 LT"))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "x264"))
        self.label_14.setText(_translate("MainWindow", "Frame Size:"))
        self.comboBox_13.setItemText(0, _translate("MainWindow", "2160P"))
        self.comboBox_13.setItemText(1, _translate("MainWindow", "1080P"))
        self.comboBox_13.setItemText(2, _translate("MainWindow", "720P"))
        self.comboBox_13.setItemText(3, _translate("MainWindow", "Default"))
        self.label_8.setText(_translate("MainWindow", "Framerate:"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "23.976"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "24"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "25"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "29.97"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "30"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "50"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "59.94"))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "60"))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "Default"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "锁定比例模式"))
        self.label_9.setText(_translate("MainWindow", "Preset:"))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "ProRes 422"))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "ProRes 422 LT"))
        self.comboBox_9.setItemText(2, _translate("MainWindow", "x264"))
        self.label_10.setText(_translate("MainWindow", "Video Format:"))
        self.comboBox_10.setItemText(0, _translate("MainWindow", "ProRes 422"))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "ProRes 422 LT"))
        self.comboBox_10.setItemText(2, _translate("MainWindow", "x264"))
        self.label_11.setText(_translate("MainWindow", "Audio Format:"))
        self.comboBox_11.setItemText(0, _translate("MainWindow", "ProRes 422"))
        self.comboBox_11.setItemText(1, _translate("MainWindow", "ProRes 422 LT"))
        self.comboBox_11.setItemText(2, _translate("MainWindow", "x264"))
        self.label_12.setText(_translate("MainWindow", "Frame Size:"))
        self.checkBox.setText(_translate("MainWindow", "锁定比例"))
        self.label_16.setText(_translate("MainWindow", "x"))
        self.label_13.setText(_translate("MainWindow", "Framerate:"))
        self.comboBox_12.setItemText(0, _translate("MainWindow", "23.976"))
        self.comboBox_12.setItemText(1, _translate("MainWindow", "24"))
        self.comboBox_12.setItemText(2, _translate("MainWindow", "25"))
        self.comboBox_12.setItemText(3, _translate("MainWindow", "29.97"))
        self.comboBox_12.setItemText(4, _translate("MainWindow", "30"))
        self.comboBox_12.setItemText(5, _translate("MainWindow", "50"))
        self.comboBox_12.setItemText(6, _translate("MainWindow", "59.94"))
        self.comboBox_12.setItemText(7, _translate("MainWindow", "60"))
        self.comboBox_12.setItemText(8, _translate("MainWindow", "Default"))
        self.label_15.setText(_translate("MainWindow", "Field："))
        self.comboBox_14.setItemText(0, _translate("MainWindow", "逐行"))
        self.comboBox_14.setItemText(1, _translate("MainWindow", "上场"))
        self.comboBox_14.setItemText(2, _translate("MainWindow", "下场"))
        self.comboBox_14.setItemText(3, _translate("MainWindow", "Default"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("MainWindow", "自定义模式"))
        self.pushButton_5.setText(_translate("MainWindow", "开启扫描"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("MainWindow", "定制模式"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "深度模式(施工中)"))
        self.pushButton_4.setText(_translate("MainWindow", "..."))
        self.pushButton_3.setText(_translate("MainWindow", "Convert"))
